@echo off
setlocal enabledelayedexpansion
title ASH Room Designer - Windows Setup
color 0B

echo.
echo  ============================================================
echo   ASH Room Designer - Windows Setup
echo   Dolby Atmos 7.1.4 Home Theater over Headphones
echo  ============================================================
echo.

REM ── Check Python ─────────────────────────────────────────────
python --version >nul 2>&1
if errorlevel 1 (
    echo  [ERROR] Python not found!
    echo         Download: https://www.python.org/downloads/
    echo         Make sure to check "Add Python to PATH" during install.
    pause
    exit /b 1
)
for /f "tokens=*" %%v in ('python --version 2^>^&1') do set PYVER=%%v
echo  [OK]  %PYVER%

REM ── Detect ASH-Toolset ────────────────────────────────────────
echo.
echo  Searching for ASH-Toolset...

set ASH_FOUND=0
set ASH_PATH=

REM Check common locations
for %%p in (
    "C:\ASH-Toolset"
    "C:\Tools\ASH-Toolset"
    "C:\Program Files\ASH-Toolset"
    "C:\Program Files (x86)\ASH Toolset"
    "%USERPROFILE%\ASH-Toolset"
    "%USERPROFILE%\Documents\ASH-Toolset"
    "%USERPROFILE%\Downloads\ASH-Toolset"
    "%APPDATA%\ASH-Toolset"
) do (
    if exist %%~p\ash_toolset.py (
        set ASH_PATH=%%~p
        set ASH_FOUND=1
        echo  [OK]  Found at: %%~p
        goto :ash_found
    )
)

REM Search SourceForge install
if exist "C:\Program Files (x86)\ASH Toolset\_internal\ash_toolset.py" (
    set ASH_PATH=C:\Program Files (x86)\ASH Toolset\_internal
    set ASH_FOUND=1
    echo  [OK]  Found SourceForge install at: !ASH_PATH!
    goto :ash_found
)

:ash_not_found
echo  [WARN] ASH-Toolset not found in common locations.
echo.
echo  Options:
echo    A) Clone from GitHub:
echo       git clone https://github.com/ShanonPearce/ASH-Toolset C:\ASH-Toolset
echo.
echo    B) Download Windows version:
echo       https://sourceforge.net/projects/ash-toolset/
echo.
echo    C) Enter path manually:
set /p MANUAL_PATH="  Enter ASH-Toolset path (or press Enter to skip): "
if not "!MANUAL_PATH!"=="" (
    if exist "!MANUAL_PATH!\ash_toolset.py" (
        set ASH_PATH=!MANUAL_PATH!
        set ASH_FOUND=1
        echo  [OK]  Valid path: !MANUAL_PATH!
        goto :ash_found
    ) else (
        echo  [WARN] ash_toolset.py not found at that path. Continuing without ASH-Toolset.
    )
)

:ash_found
echo.

REM ── Install Python dependencies ───────────────────────────────
echo  Installing Python dependencies...
echo  (This may take a few minutes on first run)
echo.

pip install --quiet --upgrade fastapi uvicorn python-multipart pydantic
if errorlevel 1 (
    echo  [ERROR] Failed to install FastAPI. Check your pip installation.
    pause
    exit /b 1
)
echo  [OK]  FastAPI + Uvicorn

pip install --quiet --upgrade numpy scipy
echo  [OK]  NumPy + SciPy

pip install --quiet --upgrade sofar soundfile
echo  [OK]  sofar (SOFA support)

pip install --quiet --upgrade h5py
echo  [OK]  h5py (HDF5/SOFA files)

REM Only install full ASH deps if toolset was found
if !ASH_FOUND!==1 (
    echo.
    echo  Installing ASH-Toolset dependencies...
    pip install --quiet librosa pyfar joblib noisereduce mat73
    echo  [OK]  ASH audio libraries
)

REM ── Write environment config ──────────────────────────────────
echo.
echo  Writing configuration...

set CONFIG_FILE=%~dp0ash_env.bat
(
    echo @echo off
    echo REM ASH Room Designer - Environment Configuration
    echo REM Generated by setup_windows.bat
    echo.
    if !ASH_FOUND!==1 (
        echo set ASH_TOOLSET_PATH=!ASH_PATH!
    ) else (
        echo set ASH_TOOLSET_PATH=C:\ASH-Toolset
        echo REM ^[TODO^] Set this to your actual ASH-Toolset path
    )
    echo set ASH_OUTPUT_DIR=%USERPROFILE%\ASH-Outputs\RoomDesigner
    echo set ASH_TEMP_DIR=%TEMP%\ASH-Temp
    echo set ASH_PORT=8765
) > "!CONFIG_FILE!"

echo  [OK]  Config written to: ash_env.bat

REM ── Create output directory ───────────────────────────────────
mkdir "%USERPROFILE%\ASH-Outputs\RoomDesigner" 2>nul
echo  [OK]  Output dir: %USERPROFILE%\ASH-Outputs\RoomDesigner

REM ── Create start script ───────────────────────────────────────
set START_FILE=%~dp0start_ash_designer.bat
(
    echo @echo off
    echo call "%~dp0ash_env.bat"
    echo title ASH Room Designer Backend
    echo color 0B
    echo echo.
    echo echo  ASH Room Designer Backend starting...
    echo echo  Output: %%ASH_OUTPUT_DIR%%
    echo echo.
    echo python "%~dp0ash_backend.py"
    echo pause
) > "!START_FILE!"

echo  [OK]  Start script: start_ash_designer.bat

REM ── Summary ───────────────────────────────────────────────────
echo.
echo  ============================================================
echo   Setup complete!
echo  ============================================================
echo.
if !ASH_FOUND!==1 (
    echo  ASH-Toolset : !ASH_PATH!
) else (
    echo  ASH-Toolset : NOT FOUND (synthetic preview BRIRs will be used)
    echo                Install: git clone https://github.com/ShanonPearce/ASH-Toolset C:\ASH-Toolset
    echo                Then run setup_windows.bat again.
)
echo.
echo  NEXT STEPS:
echo  ──────────────────────────────────────────────────────────
echo   1. Double-click: start_ash_designer.bat  (starts backend)
echo   2. Open in browser: ash_room_designer.html
echo   3. Click [Connect] in the top bar
echo   4. Load preset "Home Theater" and start designing!
echo.
echo   API docs (while backend runs): http://localhost:8765/docs
echo  ──────────────────────────────────────────────────────────
echo.

set /p LAUNCH="  Launch backend now? (Y/N): "
if /i "!LAUNCH!"=="Y" (
    start "ASH Room Designer Backend" cmd /k "call ash_env.bat && python ash_backend.py"
    timeout /t 2 /nobreak >nul
    start "" ash_room_designer.html
)

pause
endlocal
